### PR TITLE
fix(treesitter): update treesitter to use new highlight naming scheme

### PR DESCRIPTION
**Pull request by A-Lamia**
## 📑 Description

Updates the highlight groups to reflect breaking changes in https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0.
Also did a general cleanup of code structure and made sure to link groups for most the legacy highlight that should be removed at some point.

### CODE REVIEW

**Comment by A-Lamia** [comment]
Don't merge this yet.

**Comment by A-Lamia** [comment]
Ok good to go.

**Comment by mehalter** [comment]
Is there a way to make this non breaking? Even if it means maintaining some old highlights for a bit? I'm away from a computer so I haven't looked at the code

**Comment by A-Lamia** [comment]
> Is there a way to make this non breaking? Even if it means maintaining some old highlights for a bit? I'm away from a computer so I haven't looked at the code

It was always none breaking i just made a mistake haha.

**Review by mehalter — APPROVED** [review]
This looks great thanks!

**Pull request merged**
