### PR TITLE
feat(treesitter): add `<?php ... ?>` highlights

### LINKED ISSUE #143: Improve php tag `<?php ... ?>` highlight
### Is your feature related to a problem?

The current state of the highlight in php `@punctuation.bracket.php` is linked to text highlight with `@punctuation.bracket`

Screenshot 2024-09-15 at 05 18 32

### Describe the new feature

Isolate php from the rest of `@punctuation.bracket` because is kinda special.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AlejandroSuero**
## 📑 Description

Improving distinction when it comes to `@punctuation.bracket.php` -> `<?php ... ?>`.

## ℹ Additional Information

Before:

Screenshot 2024-09-15 at 05 18 32

After:

Screenshot 2024-09-15 at 05 23 49

### CODE REVIEW

**Review by A-Lamia — COMMENTED** [review]
Is there a reason why this is made bold ?

**Comment by AlejandroSuero** [comment]
@A-Lamia seems that linking with keyword doesn't let to modify `bold = true`.

Screenshot 2024-09-15 at 07 31 42

With the latest commit, it's fixed.

**Review by A-Lamia — APPROVED** [review]
Thanks for the changes, LGTM!

**Comment by A-Lamia** [comment]
seems to be a problem with vimdoc, lets get the boss here as i have no idea what his magic setup is @mehalter

**Comment by mehalter** [comment]
Ah looks like the Lua language server changed their API for generating docs. I'll check it out early this upcoming week and get this fixed and merged. Sorry!

**Comment by AlejandroSuero** [comment]
@mehalter the changes seem to be on this PR https://github.com/LuaLS/lua-language-server/pull/2821 and the [official docs with `--doc_out_path`](https://luals.github.io/wiki/usage/#--doc_out_path), `--logpath` seems to be now for the cli **logs**.

**Pull request merged**
